name: folio_app_backend
description: "A Folio APP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  companies:
    path: packages/companies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
