name: companies
description: "A Dart module which manages the companies domain."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  companies_api:
    path: packages/companies_api
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  mocktail: ^1.0.2

flutter:
